# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

mode: "www"
title: Sidneys1.com
email: admin@sidneys1.com
description: >- # this means to ignore newlines until "baseurl:"
  A home for all my ramblings on subjects such as programming, cybersecurity,
  photography, videography, video games, and whatever else I see fit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sidneys1.com" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 10

markdown: kramdown
kramdown:
   math_engine: mathjax

# Build settings
theme: minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Sidneys1", title: "GitHub" }
    - { platform: rss, user_url: "/feed.xml", title: "Sidneys1.com RSS Feed" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UCoCiN9Yd8ifG1PeVb6wY0jg", title: "YouTube Channel" }
    - { platform: mastodon, user_url: "https://infosec.exchange/@Sidneys1", title: "Mastodon (infosec.exchange)" }
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-paginate

alternative_access:
  - { platform: tor, user_url: "http://sidneys77crlfslcr7zmj3msmxchgnxhrxlp3p3kbaswo7twchjnicid.onion", title: "Tor" }
  - { platform: ipfs, user_url: "https://sidneys1-com.ipns.cf-ipfs.com/", title: "IPFS (Cloudflare)" }
  - { platform: github, user_url: "https://sidneys1.github.io", title: "GitHub Pages" }

author:
  name: Sidneys1
  contact:
    - { platform: protonmail, user_url: "mailto:Sidneys1@proton.me", title: "ProtonMail"}
    - { platform: email, user_url: "mailto:admin@sSidneys1.com", title: "Site Support"}
    - { platform: matrix, user_url: "https://matrix.to/#/@sidneys1:matrix.org", title: "Matrix Chat" }
    - { platform: simplex, user_url: "https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2FSkIkI6EPd2D63F4xFKfHk7I1UGZVNn6k1QWZ5rcyr6w%3D%40smp9.simplex.im%2FQwoc8ketLODmigLCuVhCt8Eio_ruJFnj%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAtEpK9f8ocpGt_MYmDVj0FrCIorSk7PSIVI-BmxLHUHE%253D%26srv%3Djssqzccmrcws6bhmn77vgmhfjmhwlyr3u7puw4erkyoosywgl67slqqd.onion", title: "SimpleX Chat"}

# Theme settings
# minima:
  # skin: dark
  #
header_pages:
  - about.markdown
  - tags.html
  - categories.html
  - series.html
show_excerpts: true

# TOC Settings
toc:
 min_level: 1
 max_level: 3
#  list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- Makefile
- github_pages
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
- .htaccess
- _redirects

defaults:
  - scope:
      path: "assets/404"
    values:
      "404": true
